// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniFiStoreWatcher.Web.Data;

#nullable disable

namespace UniFiStoreWatcher.Web.Data.Migrations
{
    [DbContext(typeof(UniFiStoreWatcherDbContext))]
    [Migration("20260327122649_SeedInitialProducts")]
    partial class SeedInitialProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinDelayBetweenRequestsSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<int>("PollIntervalMaxSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollIntervalMinSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RetryBaseDelaySeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VapidPrivateKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("VapidPublicKey")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxRetryAttempts = 3,
                            MinDelayBetweenRequestsSeconds = 5,
                            Nickname = "Stock Monitor",
                            PollIntervalMaxSeconds = 90,
                            PollIntervalMinSeconds = 30,
                            RetryBaseDelaySeconds = 2
                        });
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.NotificationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("NotificationConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = 621355968000000000L,
                            DisplayName = "Browser Push",
                            IsEnabled = true,
                            ProviderType = "BrowserPush",
                            UpdatedAtUtc = 621355968000000000L
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = 621355968000000000L,
                            DisplayName = "Email",
                            IsEnabled = false,
                            ProviderType = "Email",
                            UpdatedAtUtc = 621355968000000000L
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = 621355968000000000L,
                            DisplayName = "SMS (Twilio)",
                            IsEnabled = false,
                            ProviderType = "Sms",
                            UpdatedAtUtc = 621355968000000000L
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = 621355968000000000L,
                            DisplayName = "Microsoft Teams",
                            IsEnabled = false,
                            ProviderType = "Teams",
                            UpdatedAtUtc = 621355968000000000L
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = 621355968000000000L,
                            DisplayName = "Discord",
                            IsEnabled = false,
                            ProviderType = "Discord",
                            UpdatedAtUtc = 621355968000000000L
                        });
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("NotificationConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SentAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockTransitionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NotificationConfigId");

                    b.HasIndex("StockTransitionId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveErrors")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastPollAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastStateChangeAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("NextPollDueAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PollCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PreviousState")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscribedEvents")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasFilter("[ProductCode] IS NOT NULL");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("IsActive", "NextPollDueAtUtc");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = 621355968000000000L,
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UNAS Pro 4",
                            NextPollDueAtUtc = 621355968000000000L,
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UNAS-Pro-4",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = 621355968000000000L,
                            Url = "https://eu.store.ui.com/eu/en/category/network-storage/products/unas-pro-4"
                        },
                        new
                        {
                            Id = 2,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = 621355968000000000L,
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UNAS Pro 8",
                            NextPollDueAtUtc = 621355968000000000L,
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UNAS-Pro-8",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = 621355968000000000L,
                            Url = "https://eu.store.ui.com/eu/en/category/network-storage/products/unas-pro-8"
                        },
                        new
                        {
                            Id = 3,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = 621355968000000000L,
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UDB IoT",
                            NextPollDueAtUtc = 621355968000000000L,
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UDB-IoT",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = 621355968000000000L,
                            Url = "https://eu.store.ui.com/eu/en/category/wifi-bridging/products/udb-iot"
                        },
                        new
                        {
                            Id = 4,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = 621355968000000000L,
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UTR",
                            NextPollDueAtUtc = 621355968000000000L,
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UTR",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = 621355968000000000L,
                            Url = "https://eu.store.ui.com/eu/en/category/wifi-special-devices/products/utr"
                        },
                        new
                        {
                            Id = 5,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = 621355968000000000L,
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UVC G6 Edge Turret",
                            NextPollDueAtUtc = 621355968000000000L,
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UVC-G6-Edge-Turret",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = 621355968000000000L,
                            Url = "https://eu.store.ui.com/eu/en/category/cameras-dome-turret/products/uvc-g6-edge-turret"
                        },
                        new
                        {
                            Id = 6,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = 621355968000000000L,
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UVC G6 Edge Dome",
                            NextPollDueAtUtc = 621355968000000000L,
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UVC-G6-Edge-Dome",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = 621355968000000000L,
                            Url = "https://eu.store.ui.com/eu/en/category/cameras-dome-turret/products/uvc-g6-edge-dome"
                        },
                        new
                        {
                            Id = 7,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = 621355968000000000L,
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UACC HDD E-24TB",
                            NextPollDueAtUtc = 621355968000000000L,
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UACC-HDD-E-24TB",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = 621355968000000000L,
                            Url = "https://eu.store.ui.com/eu/en/category/accessories-storage/collections/unifi-accessory-tech-hdd/products/uacc-hdd-e-24tb"
                        });
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.StockCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DetectedState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRetry")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ParserConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ParserEvidence")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParserStrategy")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ProductId");

                    b.ToTable("StockChecks");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.StockTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("DetectedAtUtc")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FromState")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StockCheckId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ToState")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockCheckId");

                    b.ToTable("StockTransitions");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.NotificationLog", b =>
                {
                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.NotificationConfig", "NotificationConfig")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.StockTransition", "StockTransition")
                        .WithMany()
                        .HasForeignKey("StockTransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationConfig");

                    b.Navigation("StockTransition");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.StockCheck", b =>
                {
                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.Product", "Product")
                        .WithMany("StockChecks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.StockTransition", b =>
                {
                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.Product", "Product")
                        .WithMany("StockTransitions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.StockCheck", "StockCheck")
                        .WithMany()
                        .HasForeignKey("StockCheckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockCheck");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.NotificationConfig", b =>
                {
                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.Product", b =>
                {
                    b.Navigation("StockChecks");

                    b.Navigation("StockTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
