// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniFiStoreWatcher.Web.Data;

#nullable disable

namespace UniFiStoreWatcher.Web.Migrations
{
    [DbContext(typeof(UniFiStoreWatcherDbContext))]
    partial class UniFiStoreWatcherDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRetryAttempts")
                        .HasColumnType("int");

                    b.Property<int>("MinDelayBetweenRequestsSeconds")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PollIntervalMaxSeconds")
                        .HasColumnType("int");

                    b.Property<int>("PollIntervalMinSeconds")
                        .HasColumnType("int");

                    b.Property<int>("RetryBaseDelaySeconds")
                        .HasColumnType("int");

                    b.Property<string>("VapidPrivateKey")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VapidPublicKey")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxRetryAttempts = 3,
                            MinDelayBetweenRequestsSeconds = 5,
                            Nickname = "Stock Monitor",
                            PollIntervalMaxSeconds = 90,
                            PollIntervalMinSeconds = 30,
                            RetryBaseDelaySeconds = 2
                        });
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.NotificationConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SettingsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.ToTable("NotificationConfigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Browser Push",
                            IsEnabled = true,
                            ProviderType = "BrowserPush",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 2,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Email",
                            IsEnabled = false,
                            ProviderType = "Email",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 3,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "SMS (Twilio)",
                            IsEnabled = false,
                            ProviderType = "Sms",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 4,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Microsoft Teams",
                            IsEnabled = false,
                            ProviderType = "Teams",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = 5,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DisplayName = "Discord",
                            IsEnabled = false,
                            ProviderType = "Discord",
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.NotificationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationConfigId")
                        .HasColumnType("int");

                    b.Property<string>("ProviderType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("SentAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("StockTransitionId")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("NotificationConfigId");

                    b.HasIndex("StockTransitionId");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsecutiveErrors")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CurrentState")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("ImageUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastPollAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastStateChangeAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LocalImagePath")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTimeOffset>("NextPollDueAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PollCount")
                        .HasColumnType("int");

                    b.Property<int>("PreviousState")
                        .HasColumnType("int");

                    b.Property<string>("ProductCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SubscribedEvents")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCode")
                        .IsUnique()
                        .HasFilter("[ProductCode] IS NOT NULL");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.HasIndex("IsActive", "NextPollDueAtUtc");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UNAS Pro 4",
                            NextPollDueAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UNAS-Pro-4",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Url = "https://eu.store.ui.com/eu/en/category/network-storage/products/unas-pro-4"
                        },
                        new
                        {
                            Id = 2,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UNAS Pro 8",
                            NextPollDueAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UNAS-Pro-8",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Url = "https://eu.store.ui.com/eu/en/category/network-storage/products/unas-pro-8"
                        },
                        new
                        {
                            Id = 3,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UDB IoT",
                            NextPollDueAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UDB-IoT",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Url = "https://eu.store.ui.com/eu/en/category/wifi-bridging/products/udb-iot"
                        },
                        new
                        {
                            Id = 4,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UTR",
                            NextPollDueAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UTR",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Url = "https://eu.store.ui.com/eu/en/category/wifi-special-devices/products/utr"
                        },
                        new
                        {
                            Id = 5,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UVC G6 Edge Turret",
                            NextPollDueAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UVC-G6-Edge-Turret",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Url = "https://eu.store.ui.com/eu/en/category/cameras-dome-turret/products/uvc-g6-edge-turret"
                        },
                        new
                        {
                            Id = 6,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UVC G6 Edge Dome",
                            NextPollDueAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UVC-G6-Edge-Dome",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Url = "https://eu.store.ui.com/eu/en/category/cameras-dome-turret/products/uvc-g6-edge-dome"
                        },
                        new
                        {
                            Id = 7,
                            ConsecutiveErrors = 0,
                            CreatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CurrentState = 0,
                            ErrorCount = 0,
                            IsActive = true,
                            Name = "UACC HDD E-24TB",
                            NextPollDueAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            PollCount = 0,
                            PreviousState = 0,
                            ProductCode = "UACC-HDD-E-24TB",
                            SubscribedEvents = 1,
                            UpdatedAtUtc = new DateTimeOffset(new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Url = "https://eu.store.ui.com/eu/en/category/accessories-storage/collections/unifi-accessory-tech-hdd/products/uacc-hdd-e-24tb"
                        });
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.PushSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.StockCheck", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DetectedState")
                        .HasColumnType("int");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsRetry")
                        .HasColumnType("bit");

                    b.Property<double?>("ParserConfidence")
                        .HasColumnType("float");

                    b.Property<string>("ParserEvidence")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ParserStrategy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("RetryAttempt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("ProductId");

                    b.ToTable("StockChecks");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.StockTransition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DetectedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FromState")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<long>("StockCheckId")
                        .HasColumnType("bigint");

                    b.Property<int>("ToState")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetectedAtUtc");

                    b.HasIndex("ProductId");

                    b.HasIndex("StockCheckId");

                    b.ToTable("StockTransitions");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.NotificationLog", b =>
                {
                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.NotificationConfig", "NotificationConfig")
                        .WithMany("NotificationLogs")
                        .HasForeignKey("NotificationConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.StockTransition", "StockTransition")
                        .WithMany()
                        .HasForeignKey("StockTransitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NotificationConfig");

                    b.Navigation("StockTransition");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.StockCheck", b =>
                {
                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.Product", "Product")
                        .WithMany("StockChecks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.StockTransition", b =>
                {
                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.Product", "Product")
                        .WithMany("StockTransitions")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UniFiStoreWatcher.Web.Data.Entities.StockCheck", "StockCheck")
                        .WithMany()
                        .HasForeignKey("StockCheckId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StockCheck");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.NotificationConfig", b =>
                {
                    b.Navigation("NotificationLogs");
                });

            modelBuilder.Entity("UniFiStoreWatcher.Web.Data.Entities.Product", b =>
                {
                    b.Navigation("StockChecks");

                    b.Navigation("StockTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
